package enumTables;

public enum ProductConsole {
	_3DO, ATARI_JAGUAR, DREAMCAST, GAME_BOY, GAME_BOY_ADVANCE, GAME_BOY_COLOR,
	GAMECUBE, GENESIS, NINTENDO, NINTENDO_64, NINTENDO_DS, PC, PLAYSTATION, PLAYSTATIN_2,
	PLAYSTATION_3, SEGA_CD, SEGA_MASTER_SYSTEM, SEGA_SATURN, SUPER_NINTENDO, WII_U,
	XBOX, XBOX_360
}
