package enumTables;

public enum Province {
	ALBERTA, BRITISH_COLUMBIA, ONTARIO, QUEBEC, NOVA_SCOTIA,
	NEWFOUNDLAND_AND_LABRADOR, NEW_BRUNSWICK, PRINCE_EDWARD_ISLAND,
	MANITOBA, YUKON_TERRITORY, NORTHWEST_TERRITORY, NUNAVUT, SASKATCHEWAN 
}
